export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_COIN = 'FETCH_COIN';
export const FETCH_COIN_SUCCESS = 'FETCH_COIN_SUCCESS';
export const FETCH_COIN_FAILURE = 'FETCH_COIN_FAILURE';
